// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package cn.bytes.jtim.core.channel.protocol.protobuf;

/**
 * Protobuf type {@code AuthResponse}
 */
public final class AuthResponse extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:AuthResponse)
        AuthResponseOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use AuthResponse.newBuilder() to construct.
    private AuthResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private AuthResponse() {
        status_ = 0;
        errCode_ = "";
        errMsg_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private AuthResponse(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownFieldProto3(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 8: {

                        status_ = input.readInt32();
                        break;
                    }
                    case 18: {
                        String s = input.readStringRequireUtf8();

                        errCode_ = s;
                        break;
                    }
                    case 26: {
                        String s = input.readStringRequireUtf8();

                        errMsg_ = s;
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return cn.bytes.jtim.core.protocol.protobuf.MessageContent.internal_static_AuthResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return cn.bytes.jtim.core.protocol.protobuf.MessageContent.internal_static_AuthResponse_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        cn.bytes.jtim.core.protocol.protobuf.AuthResponse.class, cn.bytes.jtim.core.protocol.protobuf.AuthResponse.Builder.class);
    }

    /**
     * Protobuf enum {@code AuthResponse.Status}
     */
    public enum Status
            implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>OK = 0;</code>
         */
        OK(0),
        /**
         * <code>ERR = -1;</code>
         */
        ERR(-1),
        UNRECOGNIZED(-1),
        ;

        /**
         * <code>OK = 0;</code>
         */
        public static final int OK_VALUE = 0;
        /**
         * <code>ERR = -1;</code>
         */
        public static final int ERR_VALUE = -1;

        public final int getNumber() {
            if (this == UNRECOGNIZED) {
                throw new IllegalArgumentException(
                        "Can't get the number of an unknown enum value.");
            }
            return value;
        }

        /**
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @Deprecated
        public static Status valueOf(int value) {
            return forNumber(value);
        }

        public static Status forNumber(int value) {
            switch (value) {
                case 0:
                    return OK;
                case -1:
                    return ERR;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<Status>
        internalGetValueMap() {
            return internalValueMap;
        }

        private static final com.google.protobuf.Internal.EnumLiteMap<
                Status> internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<Status>() {
                    public Status findValueByNumber(int number) {
                        return Status.forNumber(number);
                    }
                };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
            return getDescriptor().getValues().get(ordinal());
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
            return getDescriptor();
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
            return cn.bytes.jtim.core.protocol.protobuf.AuthResponse.getDescriptor().getEnumTypes().get(0);
        }

        private static final Status[] VALUES = values();

        public static Status valueOf(
                com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new IllegalArgumentException(
                        "EnumValueDescriptor is not for this type.");
            }
            if (desc.getIndex() == -1) {
                return UNRECOGNIZED;
            }
            return VALUES[desc.getIndex()];
        }

        private final int value;

        private Status(int value) {
            this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:AuthResponse.Status)
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;

    /**
     * <code>int32 status = 1;</code>
     */
    public int getStatus() {
        return status_;
    }

    public static final int ERR_CODE_FIELD_NUMBER = 2;
    private volatile Object errCode_;

    /**
     * <pre>
     * 错误编码
     * </pre>
     *
     * <code>string err_code = 2;</code>
     */
    public String getErrCode() {
        Object ref = errCode_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            errCode_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * 错误编码
     * </pre>
     *
     * <code>string err_code = 2;</code>
     */
    public com.google.protobuf.ByteString
    getErrCodeBytes() {
        Object ref = errCode_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            errCode_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int ERR_MSG_FIELD_NUMBER = 3;
    private volatile Object errMsg_;

    /**
     * <pre>
     * 错误描述
     * </pre>
     *
     * <code>string err_msg = 3;</code>
     */
    public String getErrMsg() {
        Object ref = errMsg_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            errMsg_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * 错误描述
     * </pre>
     *
     * <code>string err_msg = 3;</code>
     */
    public com.google.protobuf.ByteString
    getErrMsgBytes() {
        Object ref = errMsg_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            errMsg_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (status_ != 0) {
            output.writeInt32(1, status_);
        }
        if (!getErrCodeBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errCode_);
        }
        if (!getErrMsgBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, errMsg_);
        }
        unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (status_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(1, status_);
        }
        if (!getErrCodeBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errCode_);
        }
        if (!getErrMsgBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, errMsg_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof cn.bytes.jtim.core.protocol.protobuf.AuthResponse)) {
            return super.equals(obj);
        }
        cn.bytes.jtim.core.protocol.protobuf.AuthResponse other = (cn.bytes.jtim.core.protocol.protobuf.AuthResponse) obj;

        boolean result = true;
        result = result && (getStatus()
                == other.getStatus());
        result = result && getErrCode()
                .equals(other.getErrCode());
        result = result && getErrMsg()
                .equals(other.getErrMsg());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getStatus();
        hash = (37 * hash) + ERR_CODE_FIELD_NUMBER;
        hash = (53 * hash) + getErrCode().hashCode();
        hash = (37 * hash) + ERR_MSG_FIELD_NUMBER;
        hash = (53 * hash) + getErrMsg().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static cn.bytes.jtim.core.protocol.protobuf.AuthResponse parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.bytes.jtim.core.protocol.protobuf.AuthResponse parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.bytes.jtim.core.protocol.protobuf.AuthResponse parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.bytes.jtim.core.protocol.protobuf.AuthResponse parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.bytes.jtim.core.protocol.protobuf.AuthResponse parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.bytes.jtim.core.protocol.protobuf.AuthResponse parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.bytes.jtim.core.protocol.protobuf.AuthResponse parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static cn.bytes.jtim.core.protocol.protobuf.AuthResponse parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.bytes.jtim.core.protocol.protobuf.AuthResponse parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static cn.bytes.jtim.core.protocol.protobuf.AuthResponse parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.bytes.jtim.core.protocol.protobuf.AuthResponse parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static cn.bytes.jtim.core.protocol.protobuf.AuthResponse parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(cn.bytes.jtim.core.protocol.protobuf.AuthResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code AuthResponse}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:AuthResponse)
            cn.bytes.jtim.core.protocol.protobuf.AuthResponseOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return cn.bytes.jtim.core.protocol.protobuf.MessageContent.internal_static_AuthResponse_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return cn.bytes.jtim.core.protocol.protobuf.MessageContent.internal_static_AuthResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            cn.bytes.jtim.core.protocol.protobuf.AuthResponse.class, cn.bytes.jtim.core.protocol.protobuf.AuthResponse.Builder.class);
        }

        // Construct using cn.bytes.jtim.core.protocol.protobuf.AuthResponse.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        public Builder clear() {
            super.clear();
            status_ = 0;

            errCode_ = "";

            errMsg_ = "";

            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return cn.bytes.jtim.core.protocol.protobuf.MessageContent.internal_static_AuthResponse_descriptor;
        }

        public cn.bytes.jtim.core.protocol.protobuf.AuthResponse getDefaultInstanceForType() {
            return cn.bytes.jtim.core.protocol.protobuf.AuthResponse.getDefaultInstance();
        }

        public cn.bytes.jtim.core.protocol.protobuf.AuthResponse build() {
            cn.bytes.jtim.core.protocol.protobuf.AuthResponse result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public cn.bytes.jtim.core.protocol.protobuf.AuthResponse buildPartial() {
            cn.bytes.jtim.core.protocol.protobuf.AuthResponse result = new cn.bytes.jtim.core.protocol.protobuf.AuthResponse(this);
            result.status_ = status_;
            result.errCode_ = errCode_;
            result.errMsg_ = errMsg_;
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }

        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.setField(field, value);
        }

        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof cn.bytes.jtim.core.protocol.protobuf.AuthResponse) {
                return mergeFrom((cn.bytes.jtim.core.protocol.protobuf.AuthResponse) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(cn.bytes.jtim.core.protocol.protobuf.AuthResponse other) {
            if (other == cn.bytes.jtim.core.protocol.protobuf.AuthResponse.getDefaultInstance()) return this;
            if (other.getStatus() != 0) {
                setStatus(other.getStatus());
            }
            if (!other.getErrCode().isEmpty()) {
                errCode_ = other.errCode_;
                onChanged();
            }
            if (!other.getErrMsg().isEmpty()) {
                errMsg_ = other.errMsg_;
                onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            cn.bytes.jtim.core.protocol.protobuf.AuthResponse parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (cn.bytes.jtim.core.protocol.protobuf.AuthResponse) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private int status_;

        /**
         * <code>int32 status = 1;</code>
         */
        public int getStatus() {
            return status_;
        }

        /**
         * <code>int32 status = 1;</code>
         */
        public Builder setStatus(int value) {

            status_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 status = 1;</code>
         */
        public Builder clearStatus() {

            status_ = 0;
            onChanged();
            return this;
        }

        private Object errCode_ = "";

        /**
         * <pre>
         * 错误编码
         * </pre>
         *
         * <code>string err_code = 2;</code>
         */
        public String getErrCode() {
            Object ref = errCode_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                errCode_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <pre>
         * 错误编码
         * </pre>
         *
         * <code>string err_code = 2;</code>
         */
        public com.google.protobuf.ByteString
        getErrCodeBytes() {
            Object ref = errCode_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                errCode_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * 错误编码
         * </pre>
         *
         * <code>string err_code = 2;</code>
         */
        public Builder setErrCode(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            errCode_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 错误编码
         * </pre>
         *
         * <code>string err_code = 2;</code>
         */
        public Builder clearErrCode() {

            errCode_ = getDefaultInstance().getErrCode();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 错误编码
         * </pre>
         *
         * <code>string err_code = 2;</code>
         */
        public Builder setErrCodeBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            errCode_ = value;
            onChanged();
            return this;
        }

        private Object errMsg_ = "";

        /**
         * <pre>
         * 错误描述
         * </pre>
         *
         * <code>string err_msg = 3;</code>
         */
        public String getErrMsg() {
            Object ref = errMsg_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                errMsg_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <pre>
         * 错误描述
         * </pre>
         *
         * <code>string err_msg = 3;</code>
         */
        public com.google.protobuf.ByteString
        getErrMsgBytes() {
            Object ref = errMsg_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                errMsg_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * 错误描述
         * </pre>
         *
         * <code>string err_msg = 3;</code>
         */
        public Builder setErrMsg(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            errMsg_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 错误描述
         * </pre>
         *
         * <code>string err_msg = 3;</code>
         */
        public Builder clearErrMsg() {

            errMsg_ = getDefaultInstance().getErrMsg();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 错误描述
         * </pre>
         *
         * <code>string err_msg = 3;</code>
         */
        public Builder setErrMsgBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            errMsg_ = value;
            onChanged();
            return this;
        }

        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:AuthResponse)
    }

    // @@protoc_insertion_point(class_scope:AuthResponse)
    private static final cn.bytes.jtim.core.protocol.protobuf.AuthResponse DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new cn.bytes.jtim.core.protocol.protobuf.AuthResponse();
    }

    public static cn.bytes.jtim.core.protocol.protobuf.AuthResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AuthResponse>
            PARSER = new com.google.protobuf.AbstractParser<AuthResponse>() {
        public AuthResponse parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new AuthResponse(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<AuthResponse> parser() {
        return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AuthResponse> getParserForType() {
        return PARSER;
    }

    public cn.bytes.jtim.core.protocol.protobuf.AuthResponse getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

