// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package cn.bytes.jtim.core.channel.protocol.protobuf;

public interface AuthRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:AuthRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 认证token
     * </pre>
     *
     * <code>string token = 1;</code>
     */
    String getToken();

    /**
     * <pre>
     * 认证token
     * </pre>
     *
     * <code>string token = 1;</code>
     */
    com.google.protobuf.ByteString
    getTokenBytes();

    /**
     * <pre>
     * 用户id
     * </pre>
     *
     * <code>string uid = 2;</code>
     */
    String getUid();

    /**
     * <pre>
     * 用户id
     * </pre>
     *
     * <code>string uid = 2;</code>
     */
    com.google.protobuf.ByteString
    getUidBytes();

    /**
     * <pre>
     * 发包时间
     * </pre>
     *
     * <code>int64 timestamp = 3;</code>
     */
    long getTimestamp();
}
