// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package cn.bytes.jtim.core.channel.protocol.protobuf;

public interface HeartbeatRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:HeartbeatRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes ping = 1;</code>
     */
    com.google.protobuf.ByteString getPing();
}
