// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package cn.bytes.jtim.core.channel.protocol.protobuf;

public interface KichoutRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:KichoutRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 踢人原因
     * </pre>
     *
     * <code>int32 reasion = 1;</code>
     */
    int getReasion();
}
