// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package cn.bytes.jtim.core.channel.protocol.protobuf;

public interface KichoutResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:KichoutResponse)
        com.google.protobuf.MessageOrBuilder {
}
