// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package cn.bytes.jtim.core.channel.protocol.protobuf;

public interface O2MSendRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:O2MSendRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string from = 1;</code>
     */
    String getFrom();

    /**
     * <code>string from = 1;</code>
     */
    com.google.protobuf.ByteString
    getFromBytes();

    /**
     * <code>string fromName = 2;</code>
     */
    String getFromName();

    /**
     * <code>string fromName = 2;</code>
     */
    com.google.protobuf.ByteString
    getFromNameBytes();

    /**
     * <pre>
     * 群标识
     * </pre>
     *
     * <code>string group = 3;</code>
     */
    String getGroup();

    /**
     * <pre>
     * 群标识
     * </pre>
     *
     * <code>string group = 3;</code>
     */
    com.google.protobuf.ByteString
    getGroupBytes();

    /**
     * <code>string content = 4;</code>
     */
    String getContent();

    /**
     * <code>string content = 4;</code>
     */
    com.google.protobuf.ByteString
    getContentBytes();

    /**
     * <code>string msgKey = 5;</code>
     */
    String getMsgKey();

    /**
     * <code>string msgKey = 5;</code>
     */
    com.google.protobuf.ByteString
    getMsgKeyBytes();

    /**
     * <pre>
     * 发送时间
     * </pre>
     *
     * <code>int64 timestamp = 6;</code>
     */
    long getTimestamp();
}
