// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package cn.bytes.jtim.core.channel.protocol.protobuf;

public interface O2MSendResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:O2MSendResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 消息ID
     * </pre>
     *
     * <code>string msgId = 1;</code>
     */
    String getMsgId();

    /**
     * <pre>
     * 消息ID
     * </pre>
     *
     * <code>string msgId = 1;</code>
     */
    com.google.protobuf.ByteString
    getMsgIdBytes();

    /**
     * <code>string msgKey = 2;</code>
     */
    String getMsgKey();

    /**
     * <code>string msgKey = 2;</code>
     */
    com.google.protobuf.ByteString
    getMsgKeyBytes();

    /**
     * <code>int64 timestamp = 3;</code>
     */
    long getTimestamp();
}
