// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package cn.bytes.jtim.core.channel.protocol.protobuf;

/**
 * <pre>
 * 单聊
 * </pre>
 * <p>
 * Protobuf type {@code O2OSendRequest}
 */
public final class O2OSendRequest extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:O2OSendRequest)
        O2OSendRequestOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use O2OSendRequest.newBuilder() to construct.
    private O2OSendRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private O2OSendRequest() {
        msgKey_ = "";
        from_ = "";
        fromName_ = "";
        to_ = "";
        content_ = "";
        timestamp_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private O2OSendRequest(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownFieldProto3(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        String s = input.readStringRequireUtf8();

                        msgKey_ = s;
                        break;
                    }
                    case 18: {
                        String s = input.readStringRequireUtf8();

                        from_ = s;
                        break;
                    }
                    case 26: {
                        String s = input.readStringRequireUtf8();

                        fromName_ = s;
                        break;
                    }
                    case 34: {
                        String s = input.readStringRequireUtf8();

                        to_ = s;
                        break;
                    }
                    case 42: {
                        String s = input.readStringRequireUtf8();

                        content_ = s;
                        break;
                    }
                    case 48: {

                        timestamp_ = input.readInt64();
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return cn.bytes.jtim.core.protocol.protobuf.MessageContent.internal_static_O2OSendRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return cn.bytes.jtim.core.protocol.protobuf.MessageContent.internal_static_O2OSendRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest.class, cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest.Builder.class);
    }

    public static final int MSGKEY_FIELD_NUMBER = 1;
    private volatile Object msgKey_;

    /**
     * <pre>
     * 自定义的消息标记,不能作为后期的查询条件
     * </pre>
     *
     * <code>string msgKey = 1;</code>
     */
    public String getMsgKey() {
        Object ref = msgKey_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            msgKey_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * 自定义的消息标记,不能作为后期的查询条件
     * </pre>
     *
     * <code>string msgKey = 1;</code>
     */
    public com.google.protobuf.ByteString
    getMsgKeyBytes() {
        Object ref = msgKey_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            msgKey_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int FROM_FIELD_NUMBER = 2;
    private volatile Object from_;

    /**
     * <code>string from = 2;</code>
     */
    public String getFrom() {
        Object ref = from_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            from_ = s;
            return s;
        }
    }

    /**
     * <code>string from = 2;</code>
     */
    public com.google.protobuf.ByteString
    getFromBytes() {
        Object ref = from_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            from_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int FROMNAME_FIELD_NUMBER = 3;
    private volatile Object fromName_;

    /**
     * <code>string fromName = 3;</code>
     */
    public String getFromName() {
        Object ref = fromName_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            fromName_ = s;
            return s;
        }
    }

    /**
     * <code>string fromName = 3;</code>
     */
    public com.google.protobuf.ByteString
    getFromNameBytes() {
        Object ref = fromName_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            fromName_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int TO_FIELD_NUMBER = 4;
    private volatile Object to_;

    /**
     * <code>string to = 4;</code>
     */
    public String getTo() {
        Object ref = to_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            to_ = s;
            return s;
        }
    }

    /**
     * <code>string to = 4;</code>
     */
    public com.google.protobuf.ByteString
    getToBytes() {
        Object ref = to_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            to_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int CONTENT_FIELD_NUMBER = 5;
    private volatile Object content_;

    /**
     * <code>string content = 5;</code>
     */
    public String getContent() {
        Object ref = content_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            content_ = s;
            return s;
        }
    }

    /**
     * <code>string content = 5;</code>
     */
    public com.google.protobuf.ByteString
    getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            content_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 6;
    private long timestamp_;

    /**
     * <pre>
     * 发送时间
     * </pre>
     *
     * <code>int64 timestamp = 6;</code>
     */
    public long getTimestamp() {
        return timestamp_;
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!getMsgKeyBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msgKey_);
        }
        if (!getFromBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, from_);
        }
        if (!getFromNameBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, fromName_);
        }
        if (!getToBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 4, to_);
        }
        if (!getContentBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 5, content_);
        }
        if (timestamp_ != 0L) {
            output.writeInt64(6, timestamp_);
        }
        unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getMsgKeyBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msgKey_);
        }
        if (!getFromBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, from_);
        }
        if (!getFromNameBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, fromName_);
        }
        if (!getToBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, to_);
        }
        if (!getContentBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, content_);
        }
        if (timestamp_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(6, timestamp_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest)) {
            return super.equals(obj);
        }
        cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest other = (cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest) obj;

        boolean result = true;
        result = result && getMsgKey()
                .equals(other.getMsgKey());
        result = result && getFrom()
                .equals(other.getFrom());
        result = result && getFromName()
                .equals(other.getFromName());
        result = result && getTo()
                .equals(other.getTo());
        result = result && getContent()
                .equals(other.getContent());
        result = result && (getTimestamp()
                == other.getTimestamp());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + MSGKEY_FIELD_NUMBER;
        hash = (53 * hash) + getMsgKey().hashCode();
        hash = (37 * hash) + FROM_FIELD_NUMBER;
        hash = (53 * hash) + getFrom().hashCode();
        hash = (37 * hash) + FROMNAME_FIELD_NUMBER;
        hash = (53 * hash) + getFromName().hashCode();
        hash = (37 * hash) + TO_FIELD_NUMBER;
        hash = (53 * hash) + getTo().hashCode();
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getTimestamp());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * <pre>
     * 单聊
     * </pre>
     * <p>
     * Protobuf type {@code O2OSendRequest}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:O2OSendRequest)
            cn.bytes.jtim.core.protocol.protobuf.O2OSendRequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return cn.bytes.jtim.core.protocol.protobuf.MessageContent.internal_static_O2OSendRequest_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return cn.bytes.jtim.core.protocol.protobuf.MessageContent.internal_static_O2OSendRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest.class, cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest.Builder.class);
        }

        // Construct using cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        public Builder clear() {
            super.clear();
            msgKey_ = "";

            from_ = "";

            fromName_ = "";

            to_ = "";

            content_ = "";

            timestamp_ = 0L;

            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return cn.bytes.jtim.core.protocol.protobuf.MessageContent.internal_static_O2OSendRequest_descriptor;
        }

        public cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest getDefaultInstanceForType() {
            return cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest.getDefaultInstance();
        }

        public cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest build() {
            cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest buildPartial() {
            cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest result = new cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest(this);
            result.msgKey_ = msgKey_;
            result.from_ = from_;
            result.fromName_ = fromName_;
            result.to_ = to_;
            result.content_ = content_;
            result.timestamp_ = timestamp_;
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }

        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.setField(field, value);
        }

        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest) {
                return mergeFrom((cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest other) {
            if (other == cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest.getDefaultInstance()) return this;
            if (!other.getMsgKey().isEmpty()) {
                msgKey_ = other.msgKey_;
                onChanged();
            }
            if (!other.getFrom().isEmpty()) {
                from_ = other.from_;
                onChanged();
            }
            if (!other.getFromName().isEmpty()) {
                fromName_ = other.fromName_;
                onChanged();
            }
            if (!other.getTo().isEmpty()) {
                to_ = other.to_;
                onChanged();
            }
            if (!other.getContent().isEmpty()) {
                content_ = other.content_;
                onChanged();
            }
            if (other.getTimestamp() != 0L) {
                setTimestamp(other.getTimestamp());
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private Object msgKey_ = "";

        /**
         * <pre>
         * 自定义的消息标记,不能作为后期的查询条件
         * </pre>
         *
         * <code>string msgKey = 1;</code>
         */
        public String getMsgKey() {
            Object ref = msgKey_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                msgKey_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <pre>
         * 自定义的消息标记,不能作为后期的查询条件
         * </pre>
         *
         * <code>string msgKey = 1;</code>
         */
        public com.google.protobuf.ByteString
        getMsgKeyBytes() {
            Object ref = msgKey_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                msgKey_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * 自定义的消息标记,不能作为后期的查询条件
         * </pre>
         *
         * <code>string msgKey = 1;</code>
         */
        public Builder setMsgKey(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            msgKey_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 自定义的消息标记,不能作为后期的查询条件
         * </pre>
         *
         * <code>string msgKey = 1;</code>
         */
        public Builder clearMsgKey() {

            msgKey_ = getDefaultInstance().getMsgKey();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 自定义的消息标记,不能作为后期的查询条件
         * </pre>
         *
         * <code>string msgKey = 1;</code>
         */
        public Builder setMsgKeyBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            msgKey_ = value;
            onChanged();
            return this;
        }

        private Object from_ = "";

        /**
         * <code>string from = 2;</code>
         */
        public String getFrom() {
            Object ref = from_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                from_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string from = 2;</code>
         */
        public com.google.protobuf.ByteString
        getFromBytes() {
            Object ref = from_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                from_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string from = 2;</code>
         */
        public Builder setFrom(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            from_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string from = 2;</code>
         */
        public Builder clearFrom() {

            from_ = getDefaultInstance().getFrom();
            onChanged();
            return this;
        }

        /**
         * <code>string from = 2;</code>
         */
        public Builder setFromBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            from_ = value;
            onChanged();
            return this;
        }

        private Object fromName_ = "";

        /**
         * <code>string fromName = 3;</code>
         */
        public String getFromName() {
            Object ref = fromName_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                fromName_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string fromName = 3;</code>
         */
        public com.google.protobuf.ByteString
        getFromNameBytes() {
            Object ref = fromName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                fromName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string fromName = 3;</code>
         */
        public Builder setFromName(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            fromName_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string fromName = 3;</code>
         */
        public Builder clearFromName() {

            fromName_ = getDefaultInstance().getFromName();
            onChanged();
            return this;
        }

        /**
         * <code>string fromName = 3;</code>
         */
        public Builder setFromNameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            fromName_ = value;
            onChanged();
            return this;
        }

        private Object to_ = "";

        /**
         * <code>string to = 4;</code>
         */
        public String getTo() {
            Object ref = to_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                to_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string to = 4;</code>
         */
        public com.google.protobuf.ByteString
        getToBytes() {
            Object ref = to_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                to_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string to = 4;</code>
         */
        public Builder setTo(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            to_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string to = 4;</code>
         */
        public Builder clearTo() {

            to_ = getDefaultInstance().getTo();
            onChanged();
            return this;
        }

        /**
         * <code>string to = 4;</code>
         */
        public Builder setToBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            to_ = value;
            onChanged();
            return this;
        }

        private Object content_ = "";

        /**
         * <code>string content = 5;</code>
         */
        public String getContent() {
            Object ref = content_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                content_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string content = 5;</code>
         */
        public com.google.protobuf.ByteString
        getContentBytes() {
            Object ref = content_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                content_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string content = 5;</code>
         */
        public Builder setContent(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            content_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string content = 5;</code>
         */
        public Builder clearContent() {

            content_ = getDefaultInstance().getContent();
            onChanged();
            return this;
        }

        /**
         * <code>string content = 5;</code>
         */
        public Builder setContentBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            content_ = value;
            onChanged();
            return this;
        }

        private long timestamp_;

        /**
         * <pre>
         * 发送时间
         * </pre>
         *
         * <code>int64 timestamp = 6;</code>
         */
        public long getTimestamp() {
            return timestamp_;
        }

        /**
         * <pre>
         * 发送时间
         * </pre>
         *
         * <code>int64 timestamp = 6;</code>
         */
        public Builder setTimestamp(long value) {

            timestamp_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 发送时间
         * </pre>
         *
         * <code>int64 timestamp = 6;</code>
         */
        public Builder clearTimestamp() {

            timestamp_ = 0L;
            onChanged();
            return this;
        }

        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:O2OSendRequest)
    }

    // @@protoc_insertion_point(class_scope:O2OSendRequest)
    private static final cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest();
    }

    public static cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<O2OSendRequest>
            PARSER = new com.google.protobuf.AbstractParser<O2OSendRequest>() {
        public O2OSendRequest parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new O2OSendRequest(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<O2OSendRequest> parser() {
        return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<O2OSendRequest> getParserForType() {
        return PARSER;
    }

    public cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

