// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: define.proto

package cn.bytes.jtim.core.protocol.protobuf;

public interface AckRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AckRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msgId = 1;</code>
   */
  java.lang.String getMsgId();
  /**
   * <code>string msgId = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsgIdBytes();
}
