// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: group.proto

package cn.bytes.jtim.core.protocol.protobuf;

/**
 * <pre>
 *创建群
 * </pre>
 *
 * Protobuf type {@code CreateRequest}
 */
public  final class CreateRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CreateRequest)
    CreateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateRequest.newBuilder() to construct.
  private CreateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateRequest() {
    name_ = "";
    describe_ = "";
    notice_ = "";
    maxMember_ = 0;
    maxManage_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            describe_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            notice_ = s;
            break;
          }
          case 32: {

            maxMember_ = input.readInt32();
            break;
          }
          case 40: {

            maxManage_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.bytes.jtim.core.protocol.protobuf.Group.internal_static_CreateRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.bytes.jtim.core.protocol.protobuf.Group.internal_static_CreateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.bytes.jtim.core.protocol.protobuf.CreateRequest.class, cn.bytes.jtim.core.protocol.protobuf.CreateRequest.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIBE_FIELD_NUMBER = 2;
  private volatile java.lang.Object describe_;
  /**
   * <pre>
   *描述
   * </pre>
   *
   * <code>string describe = 2;</code>
   */
  public java.lang.String getDescribe() {
    java.lang.Object ref = describe_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      describe_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *描述
   * </pre>
   *
   * <code>string describe = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDescribeBytes() {
    java.lang.Object ref = describe_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      describe_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOTICE_FIELD_NUMBER = 3;
  private volatile java.lang.Object notice_;
  /**
   * <pre>
   *公告
   * </pre>
   *
   * <code>string notice = 3;</code>
   */
  public java.lang.String getNotice() {
    java.lang.Object ref = notice_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      notice_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *公告
   * </pre>
   *
   * <code>string notice = 3;</code>
   */
  public com.google.protobuf.ByteString
      getNoticeBytes() {
    java.lang.Object ref = notice_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      notice_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MAXMEMBER_FIELD_NUMBER = 4;
  private int maxMember_;
  /**
   * <pre>
   *群最大人数
   * </pre>
   *
   * <code>int32 maxMember = 4;</code>
   */
  public int getMaxMember() {
    return maxMember_;
  }

  public static final int MAXMANAGE_FIELD_NUMBER = 5;
  private int maxManage_;
  /**
   * <pre>
   *最大管理人数
   * </pre>
   *
   * <code>int32 maxManage = 5;</code>
   */
  public int getMaxManage() {
    return maxManage_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!getDescribeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, describe_);
    }
    if (!getNoticeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, notice_);
    }
    if (maxMember_ != 0) {
      output.writeInt32(4, maxMember_);
    }
    if (maxManage_ != 0) {
      output.writeInt32(5, maxManage_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!getDescribeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, describe_);
    }
    if (!getNoticeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, notice_);
    }
    if (maxMember_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, maxMember_);
    }
    if (maxManage_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, maxManage_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.bytes.jtim.core.protocol.protobuf.CreateRequest)) {
      return super.equals(obj);
    }
    cn.bytes.jtim.core.protocol.protobuf.CreateRequest other = (cn.bytes.jtim.core.protocol.protobuf.CreateRequest) obj;

    boolean result = true;
    result = result && getName()
        .equals(other.getName());
    result = result && getDescribe()
        .equals(other.getDescribe());
    result = result && getNotice()
        .equals(other.getNotice());
    result = result && (getMaxMember()
        == other.getMaxMember());
    result = result && (getMaxManage()
        == other.getMaxManage());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + DESCRIBE_FIELD_NUMBER;
    hash = (53 * hash) + getDescribe().hashCode();
    hash = (37 * hash) + NOTICE_FIELD_NUMBER;
    hash = (53 * hash) + getNotice().hashCode();
    hash = (37 * hash) + MAXMEMBER_FIELD_NUMBER;
    hash = (53 * hash) + getMaxMember();
    hash = (37 * hash) + MAXMANAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMaxManage();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.bytes.jtim.core.protocol.protobuf.CreateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.bytes.jtim.core.protocol.protobuf.CreateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.bytes.jtim.core.protocol.protobuf.CreateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.bytes.jtim.core.protocol.protobuf.CreateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.bytes.jtim.core.protocol.protobuf.CreateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.bytes.jtim.core.protocol.protobuf.CreateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.bytes.jtim.core.protocol.protobuf.CreateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.bytes.jtim.core.protocol.protobuf.CreateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.bytes.jtim.core.protocol.protobuf.CreateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.bytes.jtim.core.protocol.protobuf.CreateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.bytes.jtim.core.protocol.protobuf.CreateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.bytes.jtim.core.protocol.protobuf.CreateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.bytes.jtim.core.protocol.protobuf.CreateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *创建群
   * </pre>
   *
   * Protobuf type {@code CreateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CreateRequest)
      cn.bytes.jtim.core.protocol.protobuf.CreateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.bytes.jtim.core.protocol.protobuf.Group.internal_static_CreateRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.bytes.jtim.core.protocol.protobuf.Group.internal_static_CreateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.bytes.jtim.core.protocol.protobuf.CreateRequest.class, cn.bytes.jtim.core.protocol.protobuf.CreateRequest.Builder.class);
    }

    // Construct using cn.bytes.jtim.core.protocol.protobuf.CreateRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      name_ = "";

      describe_ = "";

      notice_ = "";

      maxMember_ = 0;

      maxManage_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.bytes.jtim.core.protocol.protobuf.Group.internal_static_CreateRequest_descriptor;
    }

    public cn.bytes.jtim.core.protocol.protobuf.CreateRequest getDefaultInstanceForType() {
      return cn.bytes.jtim.core.protocol.protobuf.CreateRequest.getDefaultInstance();
    }

    public cn.bytes.jtim.core.protocol.protobuf.CreateRequest build() {
      cn.bytes.jtim.core.protocol.protobuf.CreateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public cn.bytes.jtim.core.protocol.protobuf.CreateRequest buildPartial() {
      cn.bytes.jtim.core.protocol.protobuf.CreateRequest result = new cn.bytes.jtim.core.protocol.protobuf.CreateRequest(this);
      result.name_ = name_;
      result.describe_ = describe_;
      result.notice_ = notice_;
      result.maxMember_ = maxMember_;
      result.maxManage_ = maxManage_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.bytes.jtim.core.protocol.protobuf.CreateRequest) {
        return mergeFrom((cn.bytes.jtim.core.protocol.protobuf.CreateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.bytes.jtim.core.protocol.protobuf.CreateRequest other) {
      if (other == cn.bytes.jtim.core.protocol.protobuf.CreateRequest.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getDescribe().isEmpty()) {
        describe_ = other.describe_;
        onChanged();
      }
      if (!other.getNotice().isEmpty()) {
        notice_ = other.notice_;
        onChanged();
      }
      if (other.getMaxMember() != 0) {
        setMaxMember(other.getMaxMember());
      }
      if (other.getMaxManage() != 0) {
        setMaxManage(other.getMaxManage());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cn.bytes.jtim.core.protocol.protobuf.CreateRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.bytes.jtim.core.protocol.protobuf.CreateRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object describe_ = "";
    /**
     * <pre>
     *描述
     * </pre>
     *
     * <code>string describe = 2;</code>
     */
    public java.lang.String getDescribe() {
      java.lang.Object ref = describe_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        describe_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *描述
     * </pre>
     *
     * <code>string describe = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDescribeBytes() {
      java.lang.Object ref = describe_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        describe_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *描述
     * </pre>
     *
     * <code>string describe = 2;</code>
     */
    public Builder setDescribe(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      describe_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *描述
     * </pre>
     *
     * <code>string describe = 2;</code>
     */
    public Builder clearDescribe() {
      
      describe_ = getDefaultInstance().getDescribe();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *描述
     * </pre>
     *
     * <code>string describe = 2;</code>
     */
    public Builder setDescribeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      describe_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object notice_ = "";
    /**
     * <pre>
     *公告
     * </pre>
     *
     * <code>string notice = 3;</code>
     */
    public java.lang.String getNotice() {
      java.lang.Object ref = notice_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        notice_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *公告
     * </pre>
     *
     * <code>string notice = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNoticeBytes() {
      java.lang.Object ref = notice_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        notice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *公告
     * </pre>
     *
     * <code>string notice = 3;</code>
     */
    public Builder setNotice(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      notice_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *公告
     * </pre>
     *
     * <code>string notice = 3;</code>
     */
    public Builder clearNotice() {
      
      notice_ = getDefaultInstance().getNotice();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *公告
     * </pre>
     *
     * <code>string notice = 3;</code>
     */
    public Builder setNoticeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      notice_ = value;
      onChanged();
      return this;
    }

    private int maxMember_ ;
    /**
     * <pre>
     *群最大人数
     * </pre>
     *
     * <code>int32 maxMember = 4;</code>
     */
    public int getMaxMember() {
      return maxMember_;
    }
    /**
     * <pre>
     *群最大人数
     * </pre>
     *
     * <code>int32 maxMember = 4;</code>
     */
    public Builder setMaxMember(int value) {
      
      maxMember_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *群最大人数
     * </pre>
     *
     * <code>int32 maxMember = 4;</code>
     */
    public Builder clearMaxMember() {
      
      maxMember_ = 0;
      onChanged();
      return this;
    }

    private int maxManage_ ;
    /**
     * <pre>
     *最大管理人数
     * </pre>
     *
     * <code>int32 maxManage = 5;</code>
     */
    public int getMaxManage() {
      return maxManage_;
    }
    /**
     * <pre>
     *最大管理人数
     * </pre>
     *
     * <code>int32 maxManage = 5;</code>
     */
    public Builder setMaxManage(int value) {
      
      maxManage_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *最大管理人数
     * </pre>
     *
     * <code>int32 maxManage = 5;</code>
     */
    public Builder clearMaxManage() {
      
      maxManage_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CreateRequest)
  }

  // @@protoc_insertion_point(class_scope:CreateRequest)
  private static final cn.bytes.jtim.core.protocol.protobuf.CreateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.bytes.jtim.core.protocol.protobuf.CreateRequest();
  }

  public static cn.bytes.jtim.core.protocol.protobuf.CreateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateRequest>() {
    public CreateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateRequest> getParserForType() {
    return PARSER;
  }

  public cn.bytes.jtim.core.protocol.protobuf.CreateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

