// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: define.proto

package cn.bytes.jtim.core.protocol.protobuf;

public interface DefineResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DefineResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool result = 1;</code>
   */
  boolean getResult();

  /**
   * <code>int32 ts = 2;</code>
   */
  int getTs();

  /**
   * <code>string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
