// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: group.proto

package cn.bytes.jtim.core.protocol.protobuf;

public interface ForbiddenRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ForbiddenRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string groupNumber = 1;</code>
   */
  java.lang.String getGroupNumber();
  /**
   * <code>string groupNumber = 1;</code>
   */
  com.google.protobuf.ByteString
      getGroupNumberBytes();

  /**
   * <code>string from = 2;</code>
   */
  java.lang.String getFrom();
  /**
   * <code>string from = 2;</code>
   */
  com.google.protobuf.ByteString
      getFromBytes();

  /**
   * <pre>
   *禁言目标，如果没有指定目标全员禁言
   * </pre>
   *
   * <code>repeated string targets = 3;</code>
   */
  java.util.List<java.lang.String>
      getTargetsList();
  /**
   * <pre>
   *禁言目标，如果没有指定目标全员禁言
   * </pre>
   *
   * <code>repeated string targets = 3;</code>
   */
  int getTargetsCount();
  /**
   * <pre>
   *禁言目标，如果没有指定目标全员禁言
   * </pre>
   *
   * <code>repeated string targets = 3;</code>
   */
  java.lang.String getTargets(int index);
  /**
   * <pre>
   *禁言目标，如果没有指定目标全员禁言
   * </pre>
   *
   * <code>repeated string targets = 3;</code>
   */
  com.google.protobuf.ByteString
      getTargetsBytes(int index);

  /**
   * <pre>
   *1s,1m,1h,1d 根据单位设置
   * </pre>
   *
   * <code>string time = 4;</code>
   */
  java.lang.String getTime();
  /**
   * <pre>
   *1s,1m,1h,1d 根据单位设置
   * </pre>
   *
   * <code>string time = 4;</code>
   */
  com.google.protobuf.ByteString
      getTimeBytes();
}
