// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: group.proto

package cn.bytes.jtim.core.protocol.protobuf;

public final class Group {
  private Group() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RemoveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RemoveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ForbiddenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ForbiddenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UnForbiddenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UnForbiddenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JoinRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JoinRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LeaveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LeaveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_KickRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_KickRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013group.proto\"e\n\rCreateRequest\022\014\n\004name\030\001" +
      " \001(\t\022\020\n\010describe\030\002 \001(\t\022\016\n\006notice\030\003 \001(\t\022\021" +
      "\n\tmaxMember\030\004 \001(\005\022\021\n\tmaxManage\030\005 \001(\005\"2\n\r" +
      "RemoveRequest\022\023\n\013groupNumber\030\001 \001(\t\022\014\n\004fr" +
      "om\030\002 \001(\t\"T\n\020ForbiddenRequest\022\023\n\013groupNum" +
      "ber\030\001 \001(\t\022\014\n\004from\030\002 \001(\t\022\017\n\007targets\030\003 \003(\t" +
      "\022\014\n\004time\030\004 \001(\t\"H\n\022UnForbiddenRequest\022\023\n\013" +
      "groupNumber\030\001 \001(\t\022\014\n\004from\030\002 \001(\t\022\017\n\007targe" +
      "ts\030\003 \003(\t\"0\n\013JoinRequest\022\023\n\013groupNumber\030\001" +
      " \001(\t\022\014\n\004from\030\002 \001(\t\"1\n\014LeaveRequest\022\023\n\013gr" +
      "oupNumber\030\001 \001(\t\022\014\n\004from\030\002 \001(\t\"@\n\013KickReq" +
      "uest\022\023\n\013groupNumber\030\001 \001(\t\022\014\n\004from\030\002 \001(\t\022" +
      "\016\n\006target\030\003 \001(\tB(\n$cn.bytes.jtim.core.pr" +
      "otocol.protobufP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CreateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CreateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateRequest_descriptor,
        new java.lang.String[] { "Name", "Describe", "Notice", "MaxMember", "MaxManage", });
    internal_static_RemoveRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RemoveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RemoveRequest_descriptor,
        new java.lang.String[] { "GroupNumber", "From", });
    internal_static_ForbiddenRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ForbiddenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ForbiddenRequest_descriptor,
        new java.lang.String[] { "GroupNumber", "From", "Targets", "Time", });
    internal_static_UnForbiddenRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_UnForbiddenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UnForbiddenRequest_descriptor,
        new java.lang.String[] { "GroupNumber", "From", "Targets", });
    internal_static_JoinRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_JoinRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JoinRequest_descriptor,
        new java.lang.String[] { "GroupNumber", "From", });
    internal_static_LeaveRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_LeaveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LeaveRequest_descriptor,
        new java.lang.String[] { "GroupNumber", "From", });
    internal_static_KickRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_KickRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_KickRequest_descriptor,
        new java.lang.String[] { "GroupNumber", "From", "Target", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
