// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package cn.bytes.jtim.core.protocol.protobuf;

public interface HeartbeatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HeartbeatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes pong = 1;</code>
   */
  com.google.protobuf.ByteString getPong();
}
