// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: group.proto

package cn.bytes.jtim.core.protocol.protobuf;

public interface JoinRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:JoinRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string groupNumber = 1;</code>
   */
  java.lang.String getGroupNumber();
  /**
   * <code>string groupNumber = 1;</code>
   */
  com.google.protobuf.ByteString
      getGroupNumberBytes();

  /**
   * <code>string from = 2;</code>
   */
  java.lang.String getFrom();
  /**
   * <code>string from = 2;</code>
   */
  com.google.protobuf.ByteString
      getFromBytes();
}
