// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package cn.bytes.jtim.core.protocol.protobuf;

public interface LogoutResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LogoutResponse)
    com.google.protobuf.MessageOrBuilder {
}
