// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package cn.bytes.jtim.core.protocol.protobuf;

public interface LogoutRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LogoutRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   */
  java.lang.String getToken();
  /**
   * <code>string token = 1;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>string uid = 2;</code>
   */
  java.lang.String getUid();
  /**
   * <code>string uid = 2;</code>
   */
  com.google.protobuf.ByteString
      getUidBytes();

  /**
   * <code>int64 timestamp = 3;</code>
   */
  long getTimestamp();
}
