// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package cn.bytes.jtim.core.protocol.protobuf;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Message.Cmd cmd = 1;</code>
   */
  int getCmdValue();
  /**
   * <code>.Message.Cmd cmd = 1;</code>
   */
  cn.bytes.jtim.core.protocol.protobuf.Message.Cmd getCmd();

  /**
   * <code>.AuthRequest authRequest = 2;</code>
   */
  boolean hasAuthRequest();
  /**
   * <code>.AuthRequest authRequest = 2;</code>
   */
  cn.bytes.jtim.core.protocol.protobuf.AuthRequest getAuthRequest();
  /**
   * <code>.AuthRequest authRequest = 2;</code>
   */
  cn.bytes.jtim.core.protocol.protobuf.AuthRequestOrBuilder getAuthRequestOrBuilder();

  /**
   * <code>.AuthResponse authResponse = 3;</code>
   */
  boolean hasAuthResponse();
  /**
   * <code>.AuthResponse authResponse = 3;</code>
   */
  cn.bytes.jtim.core.protocol.protobuf.AuthResponse getAuthResponse();
  /**
   * <code>.AuthResponse authResponse = 3;</code>
   */
  cn.bytes.jtim.core.protocol.protobuf.AuthResponseOrBuilder getAuthResponseOrBuilder();

  /**
   * <code>.LogoutRequest logoutRequest = 4;</code>
   */
  boolean hasLogoutRequest();
  /**
   * <code>.LogoutRequest logoutRequest = 4;</code>
   */
  cn.bytes.jtim.core.protocol.protobuf.LogoutRequest getLogoutRequest();
  /**
   * <code>.LogoutRequest logoutRequest = 4;</code>
   */
  cn.bytes.jtim.core.protocol.protobuf.LogoutRequestOrBuilder getLogoutRequestOrBuilder();

  /**
   * <code>.LogoutResponse logoutResponse = 5;</code>
   */
  boolean hasLogoutResponse();
  /**
   * <code>.LogoutResponse logoutResponse = 5;</code>
   */
  cn.bytes.jtim.core.protocol.protobuf.LogoutResponse getLogoutResponse();
  /**
   * <code>.LogoutResponse logoutResponse = 5;</code>
   */
  cn.bytes.jtim.core.protocol.protobuf.LogoutResponseOrBuilder getLogoutResponseOrBuilder();

  /**
   * <code>.KichoutRequest kichoutRequest = 6;</code>
   */
  boolean hasKichoutRequest();
  /**
   * <code>.KichoutRequest kichoutRequest = 6;</code>
   */
  cn.bytes.jtim.core.protocol.protobuf.KichoutRequest getKichoutRequest();
  /**
   * <code>.KichoutRequest kichoutRequest = 6;</code>
   */
  cn.bytes.jtim.core.protocol.protobuf.KichoutRequestOrBuilder getKichoutRequestOrBuilder();

  /**
   * <code>.KichoutResponse kichoutResponse = 7;</code>
   */
  boolean hasKichoutResponse();
  /**
   * <code>.KichoutResponse kichoutResponse = 7;</code>
   */
  cn.bytes.jtim.core.protocol.protobuf.KichoutResponse getKichoutResponse();
  /**
   * <code>.KichoutResponse kichoutResponse = 7;</code>
   */
  cn.bytes.jtim.core.protocol.protobuf.KichoutResponseOrBuilder getKichoutResponseOrBuilder();

  /**
   * <code>.HeartbeatRequest heartbeatRequest = 8;</code>
   */
  boolean hasHeartbeatRequest();
  /**
   * <code>.HeartbeatRequest heartbeatRequest = 8;</code>
   */
  cn.bytes.jtim.core.protocol.protobuf.HeartbeatRequest getHeartbeatRequest();
  /**
   * <code>.HeartbeatRequest heartbeatRequest = 8;</code>
   */
  cn.bytes.jtim.core.protocol.protobuf.HeartbeatRequestOrBuilder getHeartbeatRequestOrBuilder();

  /**
   * <code>.HeartbeatResponse heartbeatResponse = 9;</code>
   */
  boolean hasHeartbeatResponse();
  /**
   * <code>.HeartbeatResponse heartbeatResponse = 9;</code>
   */
  cn.bytes.jtim.core.protocol.protobuf.HeartbeatResponse getHeartbeatResponse();
  /**
   * <code>.HeartbeatResponse heartbeatResponse = 9;</code>
   */
  cn.bytes.jtim.core.protocol.protobuf.HeartbeatResponseOrBuilder getHeartbeatResponseOrBuilder();

  /**
   * <code>.O2OSendRequest o2oSendRequest = 10;</code>
   */
  boolean hasO2OSendRequest();
  /**
   * <code>.O2OSendRequest o2oSendRequest = 10;</code>
   */
  cn.bytes.jtim.core.protocol.protobuf.O2OSendRequest getO2OSendRequest();
  /**
   * <code>.O2OSendRequest o2oSendRequest = 10;</code>
   */
  cn.bytes.jtim.core.protocol.protobuf.O2OSendRequestOrBuilder getO2OSendRequestOrBuilder();

  /**
   * <code>.O2OSendResponse o2oSendResponse = 11;</code>
   */
  boolean hasO2OSendResponse();
  /**
   * <code>.O2OSendResponse o2oSendResponse = 11;</code>
   */
  cn.bytes.jtim.core.protocol.protobuf.O2OSendResponse getO2OSendResponse();
  /**
   * <code>.O2OSendResponse o2oSendResponse = 11;</code>
   */
  cn.bytes.jtim.core.protocol.protobuf.O2OSendResponseOrBuilder getO2OSendResponseOrBuilder();

  /**
   * <code>.O2ODistributeRequest o2oDistributeRequest = 12;</code>
   */
  boolean hasO2ODistributeRequest();
  /**
   * <code>.O2ODistributeRequest o2oDistributeRequest = 12;</code>
   */
  cn.bytes.jtim.core.protocol.protobuf.O2ODistributeRequest getO2ODistributeRequest();
  /**
   * <code>.O2ODistributeRequest o2oDistributeRequest = 12;</code>
   */
  cn.bytes.jtim.core.protocol.protobuf.O2ODistributeRequestOrBuilder getO2ODistributeRequestOrBuilder();

  /**
   * <code>.O2ODistributeResponse o2oDistributeResponse = 13;</code>
   */
  boolean hasO2ODistributeResponse();
  /**
   * <code>.O2ODistributeResponse o2oDistributeResponse = 13;</code>
   */
  cn.bytes.jtim.core.protocol.protobuf.O2ODistributeResponse getO2ODistributeResponse();
  /**
   * <code>.O2ODistributeResponse o2oDistributeResponse = 13;</code>
   */
  cn.bytes.jtim.core.protocol.protobuf.O2ODistributeResponseOrBuilder getO2ODistributeResponseOrBuilder();

  /**
   * <code>.O2MSendRequest o2mSendRequest = 14;</code>
   */
  boolean hasO2MSendRequest();
  /**
   * <code>.O2MSendRequest o2mSendRequest = 14;</code>
   */
  cn.bytes.jtim.core.protocol.protobuf.O2MSendRequest getO2MSendRequest();
  /**
   * <code>.O2MSendRequest o2mSendRequest = 14;</code>
   */
  cn.bytes.jtim.core.protocol.protobuf.O2MSendRequestOrBuilder getO2MSendRequestOrBuilder();

  /**
   * <code>.O2MSendResponse o2mSendResponse = 15;</code>
   */
  boolean hasO2MSendResponse();
  /**
   * <code>.O2MSendResponse o2mSendResponse = 15;</code>
   */
  cn.bytes.jtim.core.protocol.protobuf.O2MSendResponse getO2MSendResponse();
  /**
   * <code>.O2MSendResponse o2mSendResponse = 15;</code>
   */
  cn.bytes.jtim.core.protocol.protobuf.O2MSendResponseOrBuilder getO2MSendResponseOrBuilder();

  /**
   * <code>.O2MDistributeRequest o2mDistributeRequest = 16;</code>
   */
  boolean hasO2MDistributeRequest();
  /**
   * <code>.O2MDistributeRequest o2mDistributeRequest = 16;</code>
   */
  cn.bytes.jtim.core.protocol.protobuf.O2MDistributeRequest getO2MDistributeRequest();
  /**
   * <code>.O2MDistributeRequest o2mDistributeRequest = 16;</code>
   */
  cn.bytes.jtim.core.protocol.protobuf.O2MDistributeRequestOrBuilder getO2MDistributeRequestOrBuilder();

  /**
   * <code>.O2MDistributeResponse o2mDistributeResponse = 17;</code>
   */
  boolean hasO2MDistributeResponse();
  /**
   * <code>.O2MDistributeResponse o2mDistributeResponse = 17;</code>
   */
  cn.bytes.jtim.core.protocol.protobuf.O2MDistributeResponse getO2MDistributeResponse();
  /**
   * <code>.O2MDistributeResponse o2mDistributeResponse = 17;</code>
   */
  cn.bytes.jtim.core.protocol.protobuf.O2MDistributeResponseOrBuilder getO2MDistributeResponseOrBuilder();

  public cn.bytes.jtim.core.protocol.protobuf.Message.BodyCase getBodyCase();
}
