// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package cn.bytes.jtim.core.protocol.protobuf;

public interface O2ODistributeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:O2ODistributeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msgId = 1;</code>
   */
  java.lang.String getMsgId();
  /**
   * <code>string msgId = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsgIdBytes();

  /**
   * <code>string msgKey = 2;</code>
   */
  java.lang.String getMsgKey();
  /**
   * <code>string msgKey = 2;</code>
   */
  com.google.protobuf.ByteString
      getMsgKeyBytes();
}
