// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package cn.bytes.jtim.core.protocol.protobuf;

public interface O2ODistributeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:O2ODistributeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msgId = 1;</code>
   */
  java.lang.String getMsgId();
  /**
   * <code>string msgId = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsgIdBytes();

  /**
   * <code>string from = 2;</code>
   */
  java.lang.String getFrom();
  /**
   * <code>string from = 2;</code>
   */
  com.google.protobuf.ByteString
      getFromBytes();

  /**
   * <code>string fromName = 3;</code>
   */
  java.lang.String getFromName();
  /**
   * <code>string fromName = 3;</code>
   */
  com.google.protobuf.ByteString
      getFromNameBytes();

  /**
   * <code>string to = 4;</code>
   */
  java.lang.String getTo();
  /**
   * <code>string to = 4;</code>
   */
  com.google.protobuf.ByteString
      getToBytes();

  /**
   * <code>string content = 5;</code>
   */
  java.lang.String getContent();
  /**
   * <code>string content = 5;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>string msgKey = 6;</code>
   */
  java.lang.String getMsgKey();
  /**
   * <code>string msgKey = 6;</code>
   */
  com.google.protobuf.ByteString
      getMsgKeyBytes();

  /**
   * <pre>
   *发送时间
   * </pre>
   *
   * <code>int64 timestamp = 7;</code>
   */
  long getTimestamp();
}
