// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

package cn.bytes.jtim.core.protocol.protobuf;

public interface O2OSendRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:O2OSendRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *自定义的消息标记,不能作为后期的查询条件
   * </pre>
   *
   * <code>string msgKey = 1;</code>
   */
  java.lang.String getMsgKey();
  /**
   * <pre>
   *自定义的消息标记,不能作为后期的查询条件
   * </pre>
   *
   * <code>string msgKey = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsgKeyBytes();

  /**
   * <code>string from = 2;</code>
   */
  java.lang.String getFrom();
  /**
   * <code>string from = 2;</code>
   */
  com.google.protobuf.ByteString
      getFromBytes();

  /**
   * <code>string fromName = 3;</code>
   */
  java.lang.String getFromName();
  /**
   * <code>string fromName = 3;</code>
   */
  com.google.protobuf.ByteString
      getFromNameBytes();

  /**
   * <code>string to = 4;</code>
   */
  java.lang.String getTo();
  /**
   * <code>string to = 4;</code>
   */
  com.google.protobuf.ByteString
      getToBytes();

  /**
   * <code>string content = 5;</code>
   */
  java.lang.String getContent();
  /**
   * <code>string content = 5;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <pre>
   *发送时间
   * </pre>
   *
   * <code>int64 timestamp = 6;</code>
   */
  long getTimestamp();
}
