// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

package cn.bytes.jtim.core.protocol.protobuf;

public interface O2OSendResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:O2OSendResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msgKey = 1;</code>
   */
  java.lang.String getMsgKey();
  /**
   * <code>string msgKey = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsgKeyBytes();

  /**
   * <pre>
   *消息ID
   * </pre>
   *
   * <code>string msgId = 2;</code>
   */
  java.lang.String getMsgId();
  /**
   * <pre>
   *消息ID
   * </pre>
   *
   * <code>string msgId = 2;</code>
   */
  com.google.protobuf.ByteString
      getMsgIdBytes();

  /**
   * <pre>
   *收到单聊消息时间
   * </pre>
   *
   * <code>int64 timestamp = 3;</code>
   */
  long getTimestamp();
}
