// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

package cn.bytes.jtim.core.protocol.protobuf;

public final class Transfer {
  private Transfer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartbeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeartbeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartbeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeartbeatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_O2OSendRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_O2OSendRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_O2OSendResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_O2OSendResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_O2MSendRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_O2MSendRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_O2MSendResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_O2MSendResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016transfer.proto\" \n\020HeartbeatRequest\022\014\n\004" +
      "ping\030\001 \001(\014\"!\n\021HeartbeatResponse\022\014\n\004pong\030" +
      "\001 \001(\014\"p\n\016O2OSendRequest\022\016\n\006msgKey\030\001 \001(\t\022" +
      "\014\n\004from\030\002 \001(\t\022\020\n\010fromName\030\003 \001(\t\022\n\n\002to\030\004 " +
      "\001(\t\022\017\n\007content\030\005 \001(\t\022\021\n\ttimestamp\030\006 \001(\003\"" +
      "C\n\017O2OSendResponse\022\016\n\006msgKey\030\001 \001(\t\022\r\n\005ms" +
      "gId\030\002 \001(\t\022\021\n\ttimestamp\030\003 \001(\003\"s\n\016O2MSendR" +
      "equest\022\014\n\004from\030\001 \001(\t\022\020\n\010fromName\030\002 \001(\t\022\r" +
      "\n\005group\030\003 \001(\t\022\017\n\007content\030\004 \001(\t\022\016\n\006msgKey" +
      "\030\005 \001(\t\022\021\n\ttimestamp\030\006 \001(\003\"C\n\017O2MSendResp" +
      "onse\022\r\n\005msgId\030\001 \001(\t\022\016\n\006msgKey\030\002 \001(\t\022\021\n\tt" +
      "imestamp\030\003 \001(\003B(\n$cn.bytes.jtim.core.pro" +
      "tocol.protobufP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_HeartbeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HeartbeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeartbeatRequest_descriptor,
        new java.lang.String[] { "Ping", });
    internal_static_HeartbeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HeartbeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeartbeatResponse_descriptor,
        new java.lang.String[] { "Pong", });
    internal_static_O2OSendRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_O2OSendRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_O2OSendRequest_descriptor,
        new java.lang.String[] { "MsgKey", "From", "FromName", "To", "Content", "Timestamp", });
    internal_static_O2OSendResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_O2OSendResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_O2OSendResponse_descriptor,
        new java.lang.String[] { "MsgKey", "MsgId", "Timestamp", });
    internal_static_O2MSendRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_O2MSendRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_O2MSendRequest_descriptor,
        new java.lang.String[] { "From", "FromName", "Group", "Content", "MsgKey", "Timestamp", });
    internal_static_O2MSendResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_O2MSendResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_O2MSendResponse_descriptor,
        new java.lang.String[] { "MsgId", "MsgKey", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
