// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: group.proto

package cn.bytes.jtim.core.protocol.protobuf;

public interface UnForbiddenRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UnForbiddenRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string groupNumber = 1;</code>
   */
  java.lang.String getGroupNumber();
  /**
   * <code>string groupNumber = 1;</code>
   */
  com.google.protobuf.ByteString
      getGroupNumberBytes();

  /**
   * <code>string from = 2;</code>
   */
  java.lang.String getFrom();
  /**
   * <code>string from = 2;</code>
   */
  com.google.protobuf.ByteString
      getFromBytes();

  /**
   * <code>repeated string targets = 3;</code>
   */
  java.util.List<java.lang.String>
      getTargetsList();
  /**
   * <code>repeated string targets = 3;</code>
   */
  int getTargetsCount();
  /**
   * <code>repeated string targets = 3;</code>
   */
  java.lang.String getTargets(int index);
  /**
   * <code>repeated string targets = 3;</code>
   */
  com.google.protobuf.ByteString
      getTargetsBytes(int index);
}
